<?php

namespace AppBundle\Repository;

/**
 * DebloqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DebloqueRepository extends \Doctrine\ORM\EntityRepository
{
}
