<?php

namespace AppBundle\Repository;

/**
 * GagnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GagnerRepository extends \Doctrine\ORM\EntityRepository
{
}
