<?php

namespace AppBundle\Repository;

/**
 * OrnementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrnementRepository extends \Doctrine\ORM\EntityRepository
{
}
