<?php

namespace AppBundle\Repository;

/**
 * RecompenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecompenseRepository extends \Doctrine\ORM\EntityRepository
{
}
